### ISSUE TITLE
Crashed in release. But Ok in debug

### ISSUE THREAD

**Issue by panovvitalik** [google/java-photoslibrary#15]
When running in debug mode - everything ok.
But if I gneretaed apk and run app from play market - it will be crashed with following message:

Failed uploading photo to Google Photos.
Error cause:
java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
Resume url: Optional.empty
java.lang.Exception: Error cause:
java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
java.lang.NoSuchMethodError: No static method join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-oj.jar)
Resume url: Optional.empty
at vitalypanov.phototracker.googlephotos.GooglePhotosAPIHelper.upload(GooglePhotosAPIHelper.java:175)
at vitalypanov.phototracker.googlephotos.GooglePhotos.upload(GooglePhotos.java:309)
at vitalypanov.phototracker.googlephotos.GooglePhotosUploadTask.doInBackground(GooglePhotosUploadTask.java:125)
at vitalypanov.phototracker.googlephotos.GooglePhotosUploadTask.doInBackground(GooglePhotosUploadTask.java:21)
at android.os.AsyncTask$2.call(AsyncTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)

**Comment by panovvitalik** [comment]
I was cut off using of this "shi..." library from my project.
And reimplemented all work with direct REST calls. "Thank you"

So question is not actual.
