### ISSUE TITLE
crash with last version grpc-okhttp (1.31.0)

### ISSUE THREAD

**Issue by benju69** [google/java-photoslibrary#36]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/HttpUrl$Builder;
	at io.grpc.okhttp.OkHttpClientTransport.createHttpProxyRequest(OkHttpClientTransport.java:710)
	at io.grpc.okhttp.OkHttpClientTransport.createHttpProxySocket(OkHttpClientTransport.java:662)
	at io.grpc.okhttp.OkHttpClientTransport.access$1100(OkHttpClientTransport.java:108)
	at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:558)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.okhttp.HttpUrl$Builder" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.invaderscorp.polagram-ASZRU4IFgn74R2g8j_Qo8A==/base.apk"],nativeLibraryDirectories=[/data/app/com.invaderscorp.polagram-ASZRU4IFgn74R2g8j_Qo8A==/lib/arm64, /data/app/com.invaderscorp.polagram-ASZRU4IFgn74R2g8j_Qo8A==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

**Comment by jfschmakeit** [comment]
What are your dependencies? It might be related to your issues in #34 ?

**Comment by jfschmakeit** [comment]
This does sound somewhat related to #34. 

Please reopen if you are still seeing this and provide your full dependency list. Note that this client library does not currently work with the `lite` versions of GRPC and related libraries which may be getting pulled in as part of the Firebase dependencies that you mentioned in #34. (The okhttp dependency seems to be required by the `firebase-perf` mentioned there. okhttp is not required by this library.)

This client library is not currently supported on Android, but you may be able to tweak the referenced dependencies to work around these issues.
