### ISSUE TITLE
Failure to initialize using R8 in full mode on Android

### ISSUE THREAD

**Issue by samsonjs** [google/java-photoslibrary#54]
We're using this library on Android and that tooling has been updated to enable R8's full optimization mode by default. This is causing a runtime failure when trying to use the SDK:

```
java.lang.ExceptionInInitializerError
	at com.google.api.gax.grpc.GaxGrpcProperties.getGrpcTokenName(Unknown Source:0)
	at com.google.photos.library.v1.internal.stub.PhotosLibraryStubSettings.defaultApiClientHeaderProviderBuilder(SourceFile:17)
	at com.google.photos.library.v1.internal.stub.PhotosLibraryStubSettings$Builder.createDefault(SourceFile:25)
	at com.google.photos.library.v1.internal.stub.PhotosLibraryStubSettings$Builder.access$400(Unknown Source:0)
	at com.google.photos.library.v1.internal.stub.PhotosLibraryStubSettings.newBuilder(SourceFile:1)
	at com.google.photos.library.v1.PhotosLibrarySettings$Builder.createDefault(Unknown Source:2)
	at com.google.photos.library.v1.PhotosLibrarySettings.newBuilder(Unknown Source:0)
	[... elided ...]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$c.run(Unknown Source:0)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [cn5{Cancelling}@59d8b6f, Dispatchers.IO]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Package.getImplementationVersion()' on a null object reference
	at com.google.api.gax.core.GaxProperties.getLibraryVersion(SourceFile:1)
	at com.google.api.gax.core.GaxProperties.getLibraryVersion(SourceFile:3)
	at com.google.api.gax.grpc.GaxGrpcProperties.<clinit>(SourceFile:15)
	... 31 more
```

The class loader isn't finding the package for `com.google.photos.api.grpc.GaxGrpcProperties` and there's a null-pointer exception in `GaxProperties.getLibraryVersion()`. I've confirmed that our app contains both of those classes so I'm at a loss as to why the class loader can't find it.

Any ideas or pointers would be very much appreciated if this isn't a bug in this library. I'm at a loss as to how to proceed.

![CleanShot 2023-06-20 at 10 42 21@2x](https://github.com/google/java-photoslibrary/assets/32487/5d6de4b7-d838-4301-bde3-ece7bfaf1975)

![CleanShot 2023-06-20 at 10 42 41@2x](https://github.com/google/java-photoslibrary/assets/32487/97d9f8ae-0244-4dd7-9e09-c8517abb1fc5)

**Comment by samsonjs** [comment]
Looks like one of our ProGuard rules for R8 is responsible for the problem here.
